#This configuration file will hold common configs to be shared among all files
spring:
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8761/eureka/ #where our registry server is located
  server:
#    enable-self-preservation: false
    peer-node-read-timeout-ms: 90000
security:
  oauth2:
    resource:
      user-info-uri: http://auth-service:8081/authentication/current
      token-info-uri: http://auth-service:8081/authentication/oauth/check_token
    client:
      client-id: mobile
      client-secret: pecai98
      accessTokenUri: http://auth-service:8081/authentication/oauth/token
      grant-type: password

logging:
  level:
    org.springframework.security: DEBUG


