spring:
  datasource:
    url: jdbc:postgresql://postgres-assignment:5432/assignment-db
    username: assignment
    password: ams
    driver-class-name: org.postgresql.Driver

server:
  servlet:
    context-path: /assignment
  port: ${PORT:0} #dynamic port
