spring:
  datasource:
    url: jdbc:postgresql://postgres-auth:5432/auth-db
    username: postgres
    password: ams
    driver-class-name: org.postgresql.Driver

server:
  servlet:
    context-path: /authentication
  port: 8081
