spring:
  datasource:
    url: jdbc:postgresql://postgres-auth:5432/auth-db
    username: postgres
    password: ams
    driver-class-name: org.postgresql.Driver

server:
  servlet:
    context-path: /authentication
  port: 8081

management:
  #  port: 9000
  security:
    enable: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enable: true
#    metrics:
#      enable: true
  metrics:
    export:
      influx:
        uri: "http://localhost:8186"